# Define the data dictionary for "Echo data"
import pandas as pd
echo_data = [
    ("edd_34_56mm", "End-diastolic dimension of the left ventricle (typical range 34–56 mm)", "mm"),
    ("esd_23_44_mm", "End-systolic dimension of the left ventricle (typical range 23–44 mm)", "mm"),
    ("lv_function", "Overall function of the left ventricle", "Text / Ordinal"),
    ("ef", "Ejection fraction of the left ventricle", "%"),
    ("fs", "Fractional shortening", "%"),
    ("rv_size", "Right ventricular size", "Text / Ordinal"),
    ("rv_function", "Right ventricular systolic function", "Text / Ordinal"),
    ("edd_rv", "End-diastolic dimension of the right ventricle", "mm"),
    ("esd_rv", "End-systolic dimension of the right ventricle", "mm"),
    ("pw_<12mm", "Posterior wall thickness of left ventricle (normal <12 mm)", "mm"),
    ("ivs_<12mm", "Interventricular septum thickness (normal <12 mm)", "mm"),
    ("Max vel A wave (0.2-0.6 m/sec)", "Peak velocity of A-wave on mitral inflow", "m/s"),
    ("Max vel E wave (0.4-1.0 m/sec)", "Peak velocity of E-wave on mitral inflow", "m/s"),
    ("la_appearance", "Visual assessment of left atrial structure", "Text / Ordinal"),
    ("la_volume", "Left atrial volume", "mL"),
    ("la_dimensions", "Left atrial dimensions", "mm"),
    ("LA Vol /BSA", "Left atrial volume indexed to body surface area", "mL/m²"),
    ("ra_dilated?", "Right atrium is dilated", "Boolean (Yes/No)"),
    ("ra_pressure_range", "Estimated right atrial pressure range", "mmHg"),
    ("pa_dimension", "Pulmonary artery dimension", "mm"),
    ("pa_pressure_range", "Estimated pulmonary artery pressure range", "mmHg"),
    ("mitral_regurgitation", "Severity of mitral valve regurgitation", "Text / Ordinal"),
    ("peak_mr_velocity", "Peak velocity of mitral regurgitation jet", "m/s"),
    ("aliasing_velocity", "Aliasing velocity for Doppler imaging", "m/s"),
    ("mr_vti", "Velocity Time Integral of mitral regurgitation", "cm"),
    ("tricuspid_regurgitation", "Severity of tricuspid valve regurgitation", "Text / Ordinal"),
    ("ivc", "Inferior vena cava dimension or appearance", "mm / Text"),
    ("lvot", "Left ventricular outflow tract dimension", "mm"),
    ("lvot_indexed", "LVOT dimension indexed to body surface area", "mm/m²"),
    ("max_lvot_velocity", "Maximum velocity in the LVOT", "m/s"),
    ("ascending_aorta", "Diameter of the ascending aorta", "mm"),
    ("ascending_aorta_indexed", "Ascending aorta diameter indexed to body surface area", "mm/m²"),
    ("aortic_arch", "Diameter of the aortic arch", "mm"),
    ("aortic_arch_indexed", "Aortic arch diameter indexed to body surface area", "mm/m²"),
    ("sinus_of_valsalva", "Diameter at sinus of Valsalva", "mm"),
    ("sinus_of_valsalva_indexed", "Sinus of Valsalva diameter indexed to body surface area", "mm/m²"),
    ("sinotubular_junction", "Diameter of the sinotubular junction", "mm"),
    ("aortic_regurgitation", "Severity of aortic valve regurgitation", "Text / Ordinal"),
    ("valve_type_a", "Type of aortic valve (e.g., bicuspid, tricuspid, prosthetic)", "Text"),
    ("if_replaced_a", "Indicates if aortic valve has been surgically replaced", "Boolean (Yes/No)"),
    ("size_a", "Size of the aortic valve prosthesis or annulus", "mm"),
    ("max_transvalvular_velocity", "Maximum velocity across the valve", "m/s"),
    ("valve_area", "Estimated valve area", "cm²"),
    ("valve_type_m", "Type of mitral valve (e.g., native, prosthetic, repaired)", "Text"),
    ("if_replaced_m", "Indicates if mitral valve has been surgically replaced", "Boolean (Yes/No)"),
    ("size_m", "Size of mitral valve prosthesis or annulus", "mm"),
    ("pisa_radius", "Proximal Isovelocity Surface Area (PISA) radius for regurgitation quantification", "mm"),
    ("e'_septal", "Septal early diastolic tissue velocity", "cm/s"),
    ("e'_lateral", "Lateral early diastolic tissue velocity", "cm/s"),
    ("E/A", "E-wave to A-wave velocity ratio on mitral inflow", "Ratio"),
    ("E/A Ratio", "Same as E/A", "Ratio"),
    ("E/A Ratio. (old)", "Historical or prior value of E/A ratio", "Ratio"),
    ("E/e' average", "Ratio of E-wave velocity to average e' tissue Doppler velocity", "Ratio"),
    ("E/e' average.1", "Repeated or alternative entry of E/e' average", "Ratio"),
    ("E/E' lateral", "Ratio of E-wave velocity to lateral e' velocity", "Ratio"),
    ("E/E' septal", "Ratio of E-wave velocity to septal e' velocity", "Ratio"),
    ("dt", "Deceleration time of E-wave", "ms"),
    ("s_wave", "Systolic wave velocity from pulmonary vein or tissue Doppler", "cm/s"),
    ("ef_<35%__consider_device_therapy", "Flag for EF < 35% suggesting consideration of device therapy", "Boolean (Yes/No)"),
    ("global_or_focal_impairment?", "Indicates if LV impairment is global or regional", "Text"),
    ("if_lvsd,_any_thrombus?", "Indicates if thrombus is present in LV with systolic dysfunction", "Boolean (Yes/No)"),
    ("pericardial_effusion_echo", "Presence of pericardial effusion on echocardiogram", "Boolean (Yes/No)"),
    ("if_pr,_specify", "Specifies presence and severity of pulmonary regurgitation", "Text"),
    ("peak_pg", "Peak pressure gradient across a valve", "mmHg"),
    ("mean_pg", "Mean pressure gradient across a valve", "mmHg"),
    ("mean_gradient", "General mean gradient across a valve (duplicate or average)", "mmHg")
]

# Create the DataFrame
echo_df = pd.DataFrame(echo_data, columns=["Header", "Description", "Units"])

echo_df.to_csv('./aspire_echo.csv', index=False)
